### ISSUE TITLE
Linker Error (LinkAssemblies task failed) for "Mapzen.Lost.Api.ILocationListener"

### ISSUE THREAD

**Issue by senorincognito** [NAXAM/xam-mapbox-android#2]
The Binding Library for Naxam.Mapbox.Droid 5.0.2 seems to have an error. After upgrading we can no longer create a Release package with active Linker. Debug builds or deactivating the Linker in general solves the Issue but isn't a reasonable solution for obvious reasons.

Truncated error message from Build output:
`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1569,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1569,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Mapzen.Lost.Api.ILocationListener' (defined in assembly 'Naxam.Mapbox.Droid, Version=5.0.2.0, Culture=neutral, PublicKeyToken=null') with scope 'Naxam.Mapzen.Lost.Droid, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Mapzen.Lost.Api.ILocationListener
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1569,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x001d3] in /Users/builder/data/lanes/4695/bc246455/source/xamarin-android/external/linker/linker/Mono.Linker.Steps/MarkStep.cs:571 
...`

**Comment by kanvuduc** [comment]
Plz check out the latest package.

**Comment by senorincognito** [comment]
Everything looks fine now. Thank you for your work.
