### ISSUE TITLE
All references really needed?

### ISSUE THREAD

**Issue by charlenni** [NAXAM/xam-mapbox-android#3]
Hello,

first of all: thank you very much for sharing this great project with us.

Are all of the references really needed for Mapbox? There are libraries like JakeWharton's Timber for logging and others, that are not related to Mapbox.

Is it possible to remove all libraries, that are not needed for Mapbox usage?

**Comment by kanvuduc** [comment]
It takes time to create a binding library.

Things aren't needed will never be there.

Plz check mvnrepository if you see that we got mistakes when doing redundant.

Cheers.

**Comment by charlenni** [comment]
I know, bindings are not an easy thing.

Ah, thank you. Now I see, that it is a Mapbox Android reference and not one from you.

Btw. I tried to compile the xam-mapbox-android project, but get errors, because Naxam.Mapzen.Lost.Droid 2.1.2.2-alpha couldn't be found.

**Comment by kanvuduc** [comment]
Plz check the latest code. I just update the binding to 5.1.0
