### ISSUE TITLE
Mapbox v10

### ISSUE THREAD

**Issue by jvreeker** [NAXAM/xam-mapbox-android#32]
Hi,

Are you going to upgrade to version 10 of mapbox.

Thanks
Jelle

**Comment by SurulirajBanu** [comment]
@tuyen-vuduc  Mapbox versions prior to v10 will stop receiving updates. Will Naxam provide a new version?
https://docs.mapbox.com/android/legacy/maps/guides/
<img width="690" alt="Screenshot 2023-03-09 at 11 12 50 AM" src="https://user-images.githubusercontent.com/85181631/224067732-61dd3245-cd16-4549-8ec3-b746ba9cb290.png">

**Comment by justin-caldicott** [comment]
Got the same warning email through from Mapbox. It would be great to know if support is planned or we should be looking at alternatives.

**Comment by tuyen-vuduc** [comment]
It's ready. Please it out. 

https://www.nuget.org/packages/Com.Mapbox.Maps.Android
